services:
  - type: web
    name: aimone-be
    env: docker
    plan: free
    healthCheckPath: /index.php
    startCommand: "/usr/bin/supervisord -c /etc/supervisord.conf"
    buildCommand: "php artisan optimize:clear && php artisan config:clear && php artisan key:generate --force && ls -l database/migrations && php artisan migrate --force && php artisan storage:link"
    envVars:
      - key: APP_URL
        value: https://${RENDER_EXTERNAL_URL}
      - key: APP_KEY
        generateValue: true
      - key: PORT
        value: 8080
      - key: DB_CONNECTION
        value: pgsql
      - fromGroup: aimone-be-secrets

envVarGroups:
  - name: aimone-be-secrets
    envVars:
      - key: R2_ACCESS_KEY_ID
        value: YOUR_R2_ACCESS_KEY_ID
      - key: R2_SECRET_ACCESS_KEY
        value: YOUR_R2_SECRET_ACCESS_KEY
      - key: R2_BUCKET
        value: YOUR_R2_BUCKET
      - key: R2_ENDPOINT
        value: YOUR_R2_ENDPOINT
      - key: R2_URL
        value: YOUR_R2_URL